### PR TITLE
[UI-14] Site Navigation

### LINKED ISSUE #9: [UI-14] Navigation Layout
### Requirements
 - Uses `nav` HTML element
 - Uses `PageSection` component
 - Navigation items
     - Text turns `navy` on hover (and modifer `navy` on active)
     - Has line above on active (Based on hash in url, we can worry about scrollspy later)
     - Clicking on item should move user to section
     - Navigation items should be passed in via page itself
         - Would require generic components to get this working properly in typescript (Feel free to ask me about implementation details)
 - Should be sticky
 - Clicking on logo should be same as home
 - Mobile responsive (Collapses into some burger thingy, we can figure out exact requirements via design and/or me)

### Mockup Reference
Screen Shot 2022-04-25 at 1 12 31 AM

### PR DESCRIPTION
**Pull request by fpunny**
Closes #9 

### Desktop
Screen Shot 2022-05-01 at 3 52 09 PM

### Tablet
Screen Shot 2022-05-01 at 3 52 40 PM

### Mobile
Screen Shot 2022-05-01 at 3 53 03 PM

### Interactions
https://user-images.githubusercontent.com/23289083/166162344-2fc8fa1f-ee18-4c45-b796-de9cce4e6e66.mov
https://user-images.githubusercontent.com/23289083/166162362-a0f08c92-1f75-4b66-b974-c1576628881c.mov

### CODE REVIEW

**Comment by fpunny** [comment]
https://user-images.githubusercontent.com/23289083/166162384-34fc4dd3-3592-41e7-9907-4a39664629ee.mov

**Comment by fpunny** [comment]
https://user-images.githubusercontent.com/23289083/166162393-fee113f0-30ea-49ba-982b-f10aa305b4ae.mov

**Review by BlazingAsher — DISMISSED** [review]
Blur doesn't work on Firefox, but that's probably fine since I doubt many people use Firefox mobile. Other than that, LGTM.

**Comment by fpunny** [comment]
> Blur doesn't work on Firefox, but that's probably fine since I doubt many people use Firefox mobile. Other than that, LGTM.

Ya it doesnt, but we have a "fallback" solution for that which works surprisingly well
https://github.com/hack-the-6ix/landing-2022/pull/17/files#diff-910cc72d74ada4faf6db06faf0230587dd2f7676b6810dcf49f412e5ce78b247R23

**Review by BlazingAsher — APPROVED** [review]
LGTM

**Pull request merged**
